
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasyHathora.Models.BillingV1
{
    using UnityEngine.Networking;
using SpeakeasyHathora.Models.Shared;
    using System.Collections.Generic;
    public class GetPaymentMethodResponse {
        public string? ContentType { get; set; }
        
        public string? GetPaymentMethod404ApplicationJSONString { get; set; }
        
        public string? GetPaymentMethod500ApplicationJSONString { get; set; }
        
    /// <summary>
    /// Ok
    /// </summary>
        public PaymentMethod? PaymentMethod { get; set; }
        
        public int StatusCode { get; set; }
        
        public UnityWebRequest? RawResponse { get; set; }
        
    }

}