
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasyHathora.Models.AppV1
{
    using System;
using UnityEngine.Networking;
using Newtonsoft.Json;
using SpeakeasyHathora.Utils;
    using System.Collections.Generic;
    public class DeleteAppRequest
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, DeleteAppRequest value, string baseUrl)
        {
            if("DeleteApp" == operationId)
            {
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);var urlString = baseUrl + $"/apps/v1/delete/{appId}";// #request-debugging Delete 
                var message = UnityWebRequest.Delete(urlString);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [DeleteAppRequest]");
        }
    }

}