
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasyHathora.Models.AppV1
{
    using System;
using UnityEngine.Networking;
using Newtonsoft.Json;
using UnityEngine;
using SpeakeasyHathora.Utils;
    using System.Collections.Generic;
    public class GetAppInfoRequest
    {
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, GetAppInfoRequest value, string baseUrl)
        {
            if("GetAppInfo" == operationId)
            {
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                // #request-debugging A, method "get"
                var urlString = baseUrl + $"/apps/v1/info/{appId}";// #request-debugging, method "Get"
                UnityWebRequest message = UnityWebRequest.Get(urlString);
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [GetAppInfoRequest]");
        }
    }

}