
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace SpeakeasyHathora.Models.RoomV1
{
    using System;
using System.Collections.Generic;
using UnityEngine.Networking;
using System.Text;
using Newtonsoft.Json;
using SpeakeasyHathora.Models.Shared;
using SpeakeasyHathora.Utils;
    using System.Collections.Generic;
    public class CreateRoomRequest
    {
        
        [JsonProperty("CreateRoomRequest")]
        public CreateRoomRequest createRoomRequest { get; set; }
        
        
        [JsonProperty("appId")]
        public string AppId { get; set; }
        
        
        [JsonProperty("roomId")]
        public string? RoomId { get; set; }
        
        internal static UnityWebRequest BuildHttpRequestMessage(string operationId, CreateRoomRequest value, string baseUrl)
        {
            if("CreateRoom" == operationId)
            {
                var queryParams = new List<string>();
                
                
                
                queryParams.Add(QueryParamSerializer.Serialize("form",true, "roomId", "", value.RoomId));
                var queryParamString = $"?{String.Join("&", queryParams)}";
                
                
                var appId = PathParamSerializer.Serialize("simple", false, value.AppId);
                
                string json = JsonConvert.SerializeObject(value.createRoomRequest, new JsonSerializerSettings(){ NullValueHandling = NullValueHandling.Ignore, Converters = new JsonConverter[] { new IsoDateTimeSerializer(), new EnumSerializer() }});var urlString = baseUrl + $"/rooms/v1/{appId}/create" + queryParamString;// #request-debugging post TODO: work in progress
                UnityWebRequest message;message = UnityWebRequest.Post(urlString, json, "application/json");
                return message;
            }
            throw new ArgumentException($"Attempt to build UnityWebRequest for invalid operationId [{operationId}] for request type [CreateRoomRequest]");
        }
    }

}